Repository ethereumjs/ethereumjs-block, pull requests merged in 2019-12, with the labels that each got.

#85 Adding script to wrap tests copied from ethereum/tests
  README.md
  scripts/wrap-ethereum-test.sh
Labels: PR state: needs review, prio: P4 nice-to-have

#86 Add github actions
  .github/workflows/block-coverage.yml
  .github/workflows/block-lint.yml
  .github/workflows/block-test.yml
  .nycrc
  README.md
  karma.conf.js
Labels: PR state: merge ready

#89 Run gh actions on PR
  .github/workflows/block-coverage.yml
  .github/workflows/block-lint.yml
  .github/workflows/block-test.yml
Labels: PR state: merge ready

#88 Removing Travis Script
  .travis.yml
  README.md
Labels: PR state: needs review

#87 HF Muir Glacier Difficulty bomb delay
  package.json
  src/header.ts
  test/difficulty.ts
  test/difficultyEIP2384.json
  test/difficultyEIP2384_random.json
  test/difficultyEIP2384_random_to20M.json
Labels: PR state: needs review, prio: P2 very important
